#!/bin/bash

set -x

tagNumber=`git branch | grep -e "^*" | cut -d' ' -f 2`

# npm run test-travis &&

git checkout master &&
git merge "$tagNumber" &&
./scripts/update_piousbox-render_version &&
npm run clean &&
npm run build &&
git add . &&
git commit -m 'auto-build on `date +%Y%m%d`' ;
git push &&
git checkout "$tagNumber" &&

echo "tgm_react build ok"
