#!/bin/bash

echo 'THIS FAILS A LOT...'
exit 5

set -x

tagNumber=`git branch | grep -e "^*" | cut -d' ' -f 2`

npm run test-travis &&

git checkout master &&
git merge "$tagNumber" &&
npm run clean &&
npm run build &&
git add . &&
git commit -m 'auto-build on `date +%Y%m%d`' ;
git push &&
git checkout "$tagNumber" &&

echo "tgm build ok"
